server:
  port: 8080

spring:
  application:
    name: there

  datasource:
    url: jdbc:mysql://there-db.cjg8pisspmbh.ap-northeast-2.rds.amazonaws.com
    username: There
    password: therezzang!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql